pull:
	docker compose -f docker-compose.hub.yml pull

prod:
	docker compose -f docker-compose.yml -f docker-compose.hub.yml up

local:
	docker compose -f docker-compose.yml -f docker-compose.local.yml up