name: Push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  push-to-registry:
    name: Build and publish images to Docker Registry
    runs-on: ubuntu-latest
    env:
      telegram-gateway: ${{ secrets.DOCKERHUB_USERNAME }}/recsys2023.telegram-gateway
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push telegram-gateway image
        uses: docker/build-push-action@v4
        with:
          context: telegram-gateway
          push: true
          tags: ${{env.telegram-gateway}}:latest
          cache-from: type=registry,ref=${{env.telegram-gateway}}:latest
          cache-to: type=inline
          platforms: linux/x86_64